variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - .cache/pip
    - .npm/
    - .textlintcache

lint:
  image: python:3.9
  before_script:
    - pip install gitlint pre-commit
  script:
    - gitlint
    - pre-commit run --all-files

textlint:
  image: nikolaik/python-nodejs
  before_script:
    - pip install poetry
    - poetry install
    - npm ci --cache .npm --prefer-offline
  script:
    - poetry run task textlint
